name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: 'https://github.com/TBXark/ChatGPT-Telegram-Workers'
        target_repo: 'https://github.com/Pregame3985/ChatGPT-Telegram-Workers'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: 'master'
